async function makeImage(d){const c=document.createElement('canvas');c.width=1200;c.height=628;const x=c.getContext('2d');x.fillStyle='#102a43';x.fillRect(0,0,1200,628);x.fillStyle='#0f766e';x.fillRect(0,0,26,628);x.fillStyle='#fff';x.font='700 30px system-ui';x.fillText('OUTREACH SNAPSHOT',70,68);x.fillStyle='#9fb3c8';x.font='20px system-ui';x.fillText(`${d.p.id} · ${d.p.source||'Prospect'}`,70,105);x.fillStyle='#fff';x.font='800 44px system-ui';let y=wrap(x,d.p.prospect||'Prospect opportunity',70,176,1060,50,3);x.fillStyle='#67e8f9';x.font='700 21px system-ui';x.fillText('WHY I’M REACHING OUT',70,y+25);x.fillStyle='#e6eef5';x.font='25px system-ui';wrap(x,d.p.need||'Remote support opportunity',70,y+63,1060,34,5);x.fillStyle='#fff';x.font='700 21px system-ui';x.fillText('Research • clear communication • documented follow-through',70,522);x.fillStyle='#9fb3c8';x.font='18px system-ui';const sender=loadSettings().senderName||'';x.fillText((sender?sender+' · ':'')+'Generated from verified CRM fields',70,566);const blob=await new Promise(r=>c.toBlob(r,'image/png'));return new File([blob],`${d.p.id}_outreach-card.png`,{type:'image/png'})}
function wrap(ctx,text,x,y,w,lh,max){let line='',lines=[];for(const word of String(text).split(/\s+/)){const test=(line+' '+word).trim();if(ctx.measureText(test).width>w&&line){lines.push(line);line=word;if(lines.length>=max)break}else line=test}if(lines.length<max&&line)lines.push(line);lines.forEach((l,i)=>ctx.fillText(l,x,y+i*lh));return y+lines.length*lh}
function downloadFile(file){const u=URL.createObjectURL(file),a=document.createElement('a');a.href=u;a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1200)}
async function shareDraft(d){const f=await makeImage(d);if(navigator.share&&navigator.canShare&&navigator.canShare({files:[f]})){try{await navigator.share({title:d.subject,text:d.body,files:[f]});toast('Android share sheet opened with image.');return}catch(e){if(e&&e.name==='AbortError')return}}downloadFile(f);openMail(d);toast('Image saved; email opened. Attach the saved image if needed.')}
function b64url(s){return btoa(unescape(encodeURIComponent(s))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function fileB64(file){const buf=await file.arrayBuffer(),bytes=new Uint8Array(buf);let bin='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)bin+=String.fromCharCode(...bytes.subarray(i,i+chunk));return btoa(bin)}
async function getGmailToken(){if(oauthToken&&Date.now()<oauthExpires-60000)return oauthToken;const clientId=loadSettings().clientId;if(!clientId)throw new Error('Add your Google OAuth Client ID in Settings first.');if(!window.google?.accounts?.oauth2)throw new Error('Google sign-in is still loading. Try again in a moment.');return await new Promise((resolve,reject)=>{const client=google.accounts.oauth2.initTokenClient({client_id:clientId,scope:'https://www.googleapis.com/auth/gmail.compose',callback:r=>{if(r.error)return reject(new Error(r.error));oauthToken=r.access_token;oauthExpires=Date.now()+(Number(r.expires_in||3600)*1000);resolve(oauthToken)}});client.requestAccessToken({prompt:oauthToken?'':'consent'})})}
async function createGmailDraft(d){if(!d.email)return toast('Add a verified email first.');try{toast('Preparing Gmail draft + image…');const token=await getGmailToken(),f=await makeImage(d),boundary='ps200_'+Date.now();const attachment=await fileB64(f);const msg=[`To: ${d.email}`,`Subject: ${d.subject}`,'MIME-Version: 1.0',`Content-Type: multipart/mixed; boundary="${boundary}"`,'',`--${boundary}`,'Content-Type: text/plain; charset="UTF-8"','Content-Transfer-Encoding: 8bit','',d.body,'',`--${boundary}`,`Content-Type: image/png; name="${f.name}"`,'Content-Transfer-Encoding: base64',`Content-Disposition: attachment; filename="${f.name}"`,'',attachment.replace(/(.{76})/g,'$1\r\n'),'',`--${boundary}--`].join('\r\n');const raw=b64url(msg);const res=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/drafts',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({message:{raw}})});if(!res.ok)throw new Error(`Gmail returned ${res.status}`);const out=await res.json();save(d.p.id,{gmailDraftId:out.id,preparedAt:new Date().toISOString()},false);toast('Gmail draft created with image attached. Open Gmail → Drafts.');renderFocus()}catch(e){toast(e.message||'Could not create Gmail draft.');}}
function backup(){const payload={exportedAt:new Date().toISOString(),data:loadState(),settings:{senderName:loadSettings().senderName||''}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});downloadFile(new File([blob],`prospect-engine-backup-${new Date().toISOString().slice(0,10)}.json`,{type:'application/json'}));}
document.querySelectorAll('.bottom [data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
$('settingsBtn').addEventListener('click',()=>{const s=loadSettings();$('senderName').value=s.senderName||'';$('clientId').value=s.clientId||'';$('settingsDialog').showModal()});
$('saveSettings').addEventListener('click',()=>{saveSettingsObj({senderName:$('senderName').value.trim(),clientId:$('clientId').value.trim()});$('settingsDialog').close();toast('Settings saved on this device.');render()});
$('closeSettings').addEventListener('click',()=>$('settingsDialog').close());
$('backupBtn').addEventListener('click',backup);
$('installBtn').addEventListener('click',async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else toast('In Chrome, use ⋮ → Add to Home screen / Install app.');});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
ensureCurrent();switchTab('focus');
