'use strict';
(()=>{
  const H=window.CRH;
  const oldQueueCard=queueCard;
  queueCard=p=>{const due=p.status==='SENT'&&isFollowDue(p),reply=p.status==='REPLIED';const meta=H.isBusiness(p)?`${esc(p.city||'Santa Clara County')} · ${esc(p.industry||'Local business')} · checked ${esc(p.verifiedAt||'source-backed')}`:`${esc(p.source)}${p.comp?' · '+esc(p.comp):''}`;const score=H.isBusiness(p)?`<span class="miniScore">Fit ${esc(p.fit)} · Tier ${esc(p.verificationTier)}</span>`:'';return `<article class="qitem ${reply?'priorityItem':due?'dueItem':''}"><div class="qitemTop"><span class="rank">#${esc(p.priority)} · ${esc(p.id)}</span><span class="badge ${statusClass(p.status)}">${reply?'REPLY':due?'FOLLOW-UP DUE':esc(p.status)}</span></div><h3>${esc(p.prospect||'Discovery slot')}</h3><div class="meta">${meta}</div>${score}<div class="qactions"><button class="btn primary" data-open="${esc(p.id)}">${reply?'Reply now':due?'Follow up now':'Work this prospect'}</button>${p.url?`<a class="btn orange" href="${esc(p.url)}" target="_blank" rel="noopener">Source</a>`:''}</div></article>`;};
  renderQueue=()=>{const a=all();$('queueView').innerHTML=`<div class="panel queueIntro"><b>Priority:</b> replies → due follow-ups → source-backed businesses with public email → legacy leads → discovery.</div><div class="queueToolbar queueToolbarV4"><input id="queueSearch" placeholder="Search all ${a.length} prospects"><select id="queueCampaign"><option value="">All prospects</option><option value="${H.CAMPAIGN}">500 verified local businesses</option><option value="LEGACY">Legacy opportunity leads</option><option value="DISCOVERY">Discovery slots</option></select><select id="queueStatus"><option value="">All statuses</option><option>CONTACT READY</option><option>DISCOVERY SLOT</option><option>SENT</option><option>REPLIED</option><option>WON / PAID</option><option>SKIP</option></select><select id="queueWave"><option value="">All waves</option>${[1,2,3,4,5,6].map(x=>`<option>${x}</option>`).join('')}</select></div><div id="queueList"></div>`;const redraw=()=>{const q=$('queueSearch').value.toLowerCase(),camp=$('queueCampaign').value,s=$('queueStatus').value,w=$('queueWave').value;const f=a.filter(p=>(!q||JSON.stringify(p).toLowerCase().includes(q))&&(!camp||p.campaign===camp)&&(!s||p.status===s)&&(!w||String(p.wave)===w)).sort((x,y)=>H.rank(x)-H.rank(y)||(Number(y.fit)||0)-(Number(x.fit)||0)||(Number(x.priority)||9999)-(Number(y.priority)||9999));$('queueList').innerHTML=f.map(queueCard).join('')||'<div class="empty">No matches.</div>';$('queueList').querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>{currentId=b.dataset.open;switchTab('focus')}));};['queueSearch','queueCampaign','queueStatus','queueWave'].forEach(id=>$(id).addEventListener('input',redraw));redraw();};
  renderStats=()=>{const c=counters(),business=all().filter(H.isBusiness),remaining=Math.max(0,c.total-c.done),postal=H.postal();$('statsView').innerHTML=`<div class="panel"><h2 style="margin-top:0;color:var(--navy)">Cashh Radar Prospect Engine</h2><div class="bigStats"><div><b>${c.total}</b><span>Total queue</span></div><div><b>${business.length}</b><span>Source-backed business leads</span></div><div><b>${c.sent}</b><span>Sent</span></div><div><b>${c.replies}</b><span>Replies</span></div><div><b>${c.won}</b><span>Won / paid</span></div><div><b>${remaining}</b><span>Remaining</span></div></div><div class="sprintCard"><strong>$200 sprint target</strong><span>Two $100 projects or one equivalent project. This is a workflow target, not an earnings guarantee.</span></div><div class="complianceStatus ${postal?'ready':'hold'}"><b>${postal?'✓ Sender compliance setup complete':'⚠ Commercial send gate is on hold'}</b><span>${postal?'Physical postal address is saved on this device.':'Add a valid physical postal address in Settings before sending the 500 business-outreach emails.'}</span></div><button class="btn primary" style="width:100%;margin-top:10px" id="resumeWork">Resume next best prospect</button></div>`;$('resumeWork').addEventListener('click',()=>{currentId=nextWorkable(currentId).id;switchTab('focus')});};
  function settingsUpgrade(){const dlg=$('settingsDialog');if(!dlg)return;if(!$('postalAddress')){const label=$('senderName')?.closest('label');if(label){const el=document.createElement('label');el.innerHTML='Physical postal address for commercial email<input id="postalAddress" autocomplete="street-address" placeholder="Street / PO Box, City, State ZIP">';label.insertAdjacentElement('afterend',el)}const help=dlg.querySelector('.help');if(help)help.insertAdjacentHTML('beforeend','<br><br><b>Commercial outreach:</b> the 500 local-business records stay send-blocked until a valid physical postal address is saved. The address is appended to commercial emails.');}}
  settingsUpgrade();
  $('settingsBtn')?.addEventListener('click',()=>{settingsUpgrade();$('postalAddress').value=H.postal();});
  $('saveSettings')?.addEventListener('click',()=>{settingsUpgrade();const s=loadSettings();saveSettingsObj({...s,senderName:$('senderName').value.trim(),clientId:$('clientId').value.trim(),postalAddress:$('postalAddress').value.trim()});setTimeout(()=>{toast('Settings saved. Commercial send gate updated.');render();},0);});
  document.addEventListener('click',e=>{const t=e.target.closest?.('[data-action="primarySend"],[data-action="share"]');if(!t||!currentId)return;const p=merge(data.find(x=>x.id===currentId));if(H.isBusiness(p)&&!H.postalReady(p)){e.preventDefault();e.stopImmediatePropagation();settingsUpgrade();$('settingsBtn').click();toast('Add a valid physical postal address before commercial outreach.');}},true);
  function enhance(){const root=$('focusView');if(!root||!currentId)return;const p=merge(data.find(x=>x.id===currentId));document.querySelector('header h1')?.replaceChildren(document.createTextNode('Cashh Radar Prospect Engine'));const sub=document.querySelector('header .head small');if(sub)sub.textContent=`${data.length} prospects • next-best-action mode`;const rank=root.querySelector('.rank');if(rank)rank.textContent=rank.textContent.replace(/of\s+200/i,`of ${data.length}`);if(!H.isBusiness(p))return;const need=root.querySelector('.need');if(need)need.innerHTML=`<b>Public business signal:</b><br>${esc(H.signal(p))}<br><br><b>Prepared content direction:</b><br>${esc(H.idea(p))}`;if(!root.querySelector('.leadIntel')){const intel=document.createElement('div');intel.className='leadIntel';intel.innerHTML=`<span>${esc(p.city)}</span><span>${esc(p.industry)}</span><span>Tier ${esc(p.verificationTier)}</span><span>Fit ${esc(p.fit)}</span><span>Checked ${esc(p.verifiedAt)}</span>`;need?.insertAdjacentElement('afterend',intel)}const rail=root.querySelector('.stepRail');if(rail&&!root.querySelector('.commercialGate')){const g=document.createElement('div');g.className=`commercialGate ${H.postalReady(p)?'ready':'hold'}`;g.innerHTML=H.postalReady(p)?'<b>✓ Commercial email preflight ready</b><span>Public email + source evidence + sender postal address saved.</span>':'<b>⚠ One-time sender setup required</b><span>Add your physical postal address in ⚙ Settings before sending this business-outreach email.</span>';rail.insertAdjacentElement('beforebegin',g)}if(!H.postalReady(p))root.querySelectorAll('[data-action="primarySend"]').forEach(b=>b.textContent='Add sender address to unlock outreach');}
  const obs=new MutationObserver(enhance);if($('focusView'))obs.observe($('focusView'),{childList:true,subtree:true});
  setTimeout(()=>{settingsUpgrade();enhance();document.title='Cashh Radar Prospect Engine';const w=document.querySelector('.welcomeCard .tinyNote');if(w)w.textContent=`You do not need to manage all ${data.length} prospects at once. The app keeps choosing the next best action.`;render();},60);
})();
